################################################################################
# USB TO UART															       #
################################################################################


[platformio]
	include_dir = ./
	src_dir = ./
	boards_dir = Boards
	description = USB TO UART
	;default_envs = debug

[env]
	monitor_speed = 115200
	monitor_filters =
		time

[env:release]
	platform = ststm32@15.4.1
	board = GD32F303CG
	board_build.ldscript = Source/Libraries/STM32F1xx/Linker/GD32F303CGT6_PROG.ld
	upload_protocol = jlink
	upload_flags =
		-ExitOnError
		1
	upload_command =
	debug_tool = jlink
	debug_svd_path = Source/Libraries/STM32F1xx/SVD/STM32F103.svd
	build_flags =
		# HAL Library.
		"-D HSE_VALUE=16000000"
		"-D USE_HAL_DRIVER"
		-includeSource/Libraries/STM32F1xx/Include/stm32f1xx.h
		-includeSource/Libraries/DataTypes/boolean.h
		-includeSource/Libraries/DataTypes/float.h
		-ISource/Libraries/CMSIS/Include
		-ISource/Libraries/STM32F1xx/Include
		-ISource/Libraries/STM32F1xx_HAL_Driver/Include

		# USB Library.
		-ISource/Libraries/STM32_USB_Device_Library

		# User code.
		-ISource
	build_src_filter =
		-<**/*>

		# HAL Library.
		+<Source/Libraries/STM32F1xx/Source/startup/startup_gd32f303cg_prog.s>
		+<Source/Libraries/STM32F1xx/Source/system_stm32f1xx.c>
		+<Source/Libraries/STM32F1xx_HAL_Driver/Source/stm32f1xx_hal.c>
		+<Source/Libraries/STM32F1xx_HAL_Driver/Source/stm32f1xx_hal_cortex.c>
		+<Source/Libraries/STM32F1xx_HAL_Driver/Source/stm32f1xx_hal_rcc.c>
		+<Source/Libraries/STM32F1xx_HAL_Driver/Source/stm32f1xx_hal_rcc_ex.c>
		+<Source/Libraries/STM32F1xx_HAL_Driver/Source/stm32f1xx_hal_gpio.c>
		+<Source/Libraries/STM32F1xx_HAL_Driver/Source/stm32f1xx_hal_usart.c>
		+<Source/Libraries/STM32F1xx_HAL_Driver/Source/stm32f1xx_hal_uart.c>
		+<Source/Libraries/STM32F1xx_HAL_Driver/Source/stm32f1xx_hal_dma.c>
		+<Source/Libraries/STM32F1xx_HAL_Driver/Source/stm32f1xx_hal_pcd.c>
		+<Source/Libraries/STM32F1xx_HAL_Driver/Source/stm32f1xx_hal_pcd_ex.c>
		+<Source/Libraries/STM32F1xx_HAL_Driver/Source/stm32f1xx_ll_usb.c>

		# USB Library.
		+<Source/Libraries/STM32_USB_Device_Library>

		# User code
		+<Source/main.c>
		+<Source/stm32f1xx_hal_msp.c>
		+<Source/stm32f1xx_it.c>
		+<Source/buffer.c>

	board_ldflags =
		-Wl,-Map=$BUILD_DIR/firmware.map
		--specs=nano.specs
		--specs=nosys.specs

[env:debug]
	extends = env:release
	build_flags =
		${env:release.build_flags}
		#${debug_uart.build_flags}
	board_ldflags =
		${env:release.board_ldflags}
		-u _printf_float
	build_src_filter =
		${env:release.build_src_filter}
		#${debug_uart.build_src_filter}
	debug_build_flags =
		-O0
		-ggdb3
		-g3

