################################################################################
# USB TO UART															       #
################################################################################


[platformio]
	include_dir = ./
	src_dir = ./
	boards_dir = Boards
	description = USB TO UART
	default_envs = usb_to_uart_debug

[env]
	monitor_speed = 115200
	monitor_filters =
		time

[common]
	platform = ststm32@15.4.1
	board = GD32F303CG
	board_build.ldscript = Source/Libraries/STM32F1xx/Linker/GD32F303CGT6_PROG.ld
	upload_protocol = jlink
	upload_flags =
		-ExitOnError
		1
	upload_command =
	debug_tool = jlink
	debug_svd_path = Source/Libraries/STM32F1xx/SVD/STM32F103.svd
	extra_scripts =
		Scripts/firmware.py

	build_flags =
		# HAL Library.
		"-D HSE_VALUE=16000000"
		"-D USE_HAL_DRIVER"
		-includeSource/Libraries/STM32F1xx/Include/stm32f1xx.h
		-includeSource/Libraries/DataTypes/boolean.h
		-includeSource/Libraries/DataTypes/float.h

		# Hardware
		-ISource/Hardware
		-ISource/Hardware/GPIO
		-ISource/Hardware/RCC
		-ISource/Hardware/USB

		# Library.
		-ISource/Libraries/CMSIS/Include
		-ISource/Libraries/STM32F1xx/Include
		-ISource/Libraries/STM32F1xx_HAL_Driver/Include
		-ISource/Libraries/STM32_USB_Device_Library
		-ISource/Libraries/Buffer

		#-ISource/Libraries/argp-standalone-master/include/argp-standalone
		#-ISource/Libraries/argp-standalone-master/src

		# User code.
		-ISource

	build_src_filter =
		-<**/*>

		# Hardware
		+<Source/Hardware/mcu_it.c>
		+<Source/Hardware/GPIO>
		+<Source/Hardware/RCC>
		+<Source/Hardware/USB>

		# Library/HAL.
		+<Source/Libraries/STM32F1xx/Source/startup/startup_gd32f303cg_prog.s>
		+<Source/Libraries/STM32F1xx/Source/system_stm32f1xx.c>
		+<Source/Libraries/STM32F1xx_HAL_Driver/Source/stm32f1xx_hal.c>
		+<Source/Libraries/STM32F1xx_HAL_Driver/Source/stm32f1xx_hal_cortex.c>
		+<Source/Libraries/STM32F1xx_HAL_Driver/Source/stm32f1xx_hal_rcc.c>
		+<Source/Libraries/STM32F1xx_HAL_Driver/Source/stm32f1xx_hal_rcc_ex.c>
		+<Source/Libraries/STM32F1xx_HAL_Driver/Source/stm32f1xx_hal_gpio.c>
		+<Source/Libraries/STM32F1xx_HAL_Driver/Source/stm32f1xx_hal_dma.c>
		+<Source/Libraries/STM32F1xx_HAL_Driver/Source/stm32f1xx_hal_pcd.c>
		+<Source/Libraries/STM32F1xx_HAL_Driver/Source/stm32f1xx_hal_pcd_ex.c>
		+<Source/Libraries/STM32F1xx_HAL_Driver/Source/stm32f1xx_ll_usb.c>

		# Library/USB.
		+<Source/Libraries/STM32_USB_Device_Library>

		# Library/Buffer.
		+<Source/Libraries/Buffer>

		#+<Source/Libraries/argp-standalone-master/src>

		# User code
		+<Source/main.c>
		+<Source/stm32f1xx_hal_msp.c>
		+<Source/stm32f1xx_it.c>
		+<Source/buffer.c>

	board_ldflags =
		-Wl,-Map=$BUILD_DIR/firmware.map
		--specs=nano.specs
		--specs=nosys.specs

[env:usb_to_uart_release]
	extends= common

	build_flags =
		${common.build_flags}
		-DUSB_TO_UART=1
		-includeSource/usb_to_uart/config.h
		-ISource/usb_to_uart

	build_src_filter =
		${common.build_src_filter}
		+<Source/usb_to_uart>
		+<Source/Libraries/STM32F1xx_HAL_Driver/Source/stm32f1xx_hal_usart.c>
		+<Source/Libraries/STM32F1xx_HAL_Driver/Source/stm32f1xx_hal_uart.c>

[env:usb_to_uart_debug]
	extends = env:usb_to_uart_release
	build_flags =
		${env:usb_to_uart_release.build_flags}
		-DDEBUG=1

	board_ldflags =
		${env:usb_to_uart_release.board_ldflags}

	build_src_filter =
		${env:usb_to_uart_release.build_src_filter}

	debug_build_flags =
		-O0
		-ggdb3
		-g3


[env:usb_to_spi_release]
	extends= common

	build_flags =
		${common.build_flags}
		-DUSB_TO_SPI=1
		-includeSource/usb_to_spi/config.h
		-ISource/usb_to_spi

	build_src_filter =
		${common.build_src_filter}
		+<Source/usb_to_spi>
		+<Source/Libraries/STM32F1xx_HAL_Driver/Source/stm32f1xx_hal_spi.c>



[env:usb_to_spi_debug]
	extends = env:usb_to_spi_release
	build_flags =
		${env:usb_to_spi_release.build_flags}
		-DDEBUG=1

	board_ldflags =
		${env:usb_to_spi_release.board_ldflags}

	build_src_filter =
		${env:usb_to_spi_release.build_src_filter}

	debug_build_flags =
		-O0
		-ggdb3
		-g3